### ISSUE TITLE
S3?

### ISSUE THREAD

**Issue by brennanerbz** [AnomalyInnovations/serverless-stack-demo-api#2]
How does the data.attachment get uploaded to S3? Is it some Amazon magic?

**Comment by jayair** [comment]
@brennanerbz the upload is done on the frontend. So the file is uploaded to S3 on the frontend and then the link to the file is stored in Dynamo.

**Comment by brennanerbz** [comment]
Is this desired and the fastest solution?

**Comment by jayair** [comment]
@brennanerbz for this use case it is. It doesn't make sense to upload it to your backend and then upload it again to S3.

However, there are cases where you'd want to do that. For example, you are creating an API that allows people to upload files.

**Comment by jayair** [comment]
@brennanerbz Just saw your message as well. Here is the chapter on how to upload a file to S3 directly from the client with the proper security credentials - http://serverless-stack.com/chapters/upload-a-file-to-s3.html

**Comment by jayair** [comment]
Closing this
