### ISSUE TITLE
Why not use aws-serverless-express?

### ISSUE THREAD

**Issue by VictorioBerra** [AnomalyInnovations/serverless-stack-demo-api#25]
https://github.com/awslabs/aws-serverless-express

Just curious, with the above package you still have APIG and Lambda, but you forward any HTTP call from APIG and lean into express for all the routing and middleware needs.

That seems so much easier than having to add extra stuff to serverless.yml, and gets you the full power of express but you keep all the benefits of APIG like caching and auth.

**Comment by jayair** [comment]
It's a good question. Lambda's are not really designed to run large applications. It is much better to have single lightweight functions per Lambda. You run into both slower cold and warm starts with a large express app.
