### ISSUE TITLE
Lambda vs. EC2

### ISSUE THREAD

**Issue by brennanerbz** [AnomalyInnovations/serverless-stack-demo-api#3]
If I'm building the backend for an MVP of my mobile app, would you recommend using the design pattern found in this repo, or a typical Express app on EC2 beanstalk instances?

**Comment by jayair** [comment]
@brennanerbz I'm not sure if this setup fits your use case (basic CRUD app + authentication + uploads). But if it does, then I would recommend it.

That being said, as a startup founder myself; I would probably go with a setup that you are most familiar with. Given that your time is probably the biggest factor.

Btw, I see your email. I'll send you a note.

**Comment by jayair** [comment]
Closing this.
