### ISSUE TITLE
Create API Local Test

### ISSUE THREAD

**Issue by bgail** [AnomalyInnovations/serverless-stack-demo-api#8]
Following this page: https://serverless-stack.com/chapters/add-a-create-note-api.html

When running: `serverless invoke local --function create --path mocks/create-event.json`
It returns:
```json
{
    "statusCode": 500,
    "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Credentials": true
    },
    "body": "{\"status\":false}"
}
```

I checked:
~/.aws/credentials
- it only contains 1 credential

~/.aws/config
region=us-east-1

In serverless.yml:
region=us-east-1 as well

In create.js:
region=us-east-1 as well

There are no other helpful messages that tell me why it returned statusCode 500. 

Please help. Thanks.

**Comment by jayair** [comment]
@bgail 500 errors should be straightforward to debug. You can try adding a `console.log` to see what is going on. Here is some more info on it https://serverless-stack.com/chapters/add-a-create-note-api.html#common-issues
